set vTableName = 'DIM_FATOR';
set vFileNameOrigin = 'DIM_FATOR.QVD';
set vFileNameOutput = 'DIM_FATOR.QVD';

$(vTableName):
LOAD
    codigo_ocorrencia3 as %KeyFator,
    codigo_ocorrencia3 as [Fator_Codigo_Ocorrencia],
    fator_nome,
    fator_aspecto,
    fator_condicionante,
    fator_area
FROM [$(vPathExtract)$(vFileNameOrigin)](QVD);


STORE $(vTableName) INTO [$(vPathTransform)$(vFileNameOutput)](qvd);

drop table $(vTableName);
 